#!/bin/bash
#This script will create at ../out
#a release version of the LiteScript compiler, in order to
#make the litescript compiler stable package for the npm repository

#set -e

VERSION=0.6
using=using
PREV=0.6

if [ ! "$using" = "using" ]; then 
    echo usage: ./release 0.6.0 using 0.5.0
    exit 1
fi

cwd=$(pwd) 
out='../../'

#--------------------------------------
# MAIN

echo compile lite-cli ${VERSION} 
echo -----------------------
echo cwd: ${cwd}
echo dest dir: ${out}

if [ ! -e "${out}/lib" ]; then 
    echo cant find /lib at ${out}
    exit 1
fi

#compile lite-cli (command line interface) v${VERSION} using ${PREV} version, w/o comments or mapsource
#node --debug-brk lite-js -use v${PREV} -noval -nomap -comments 1 -compile ../source-v${VERSION}/lite-cli -o ${out}/lib
node lite-js -use v${PREV} -noval -nomap -single -comments 0 -compile ../source-v${VERSION}/lite-cli -o ${out}lib

# lo copio al dir que usa debug-compiler
echo cp ${out}lib/lite-cli.js out/lib/lite-cli.js
cp ${out}lib/lite-cli.js out/lib/lite-cli.js
