#!/bin/bash

set -e

VERSION=$1
[ "$VERSION" = "" ] && VERSION=0.6

CWD=$(pwd)

#get main source folder: /source
cd "../.."
MAIN=$(pwd)
cd -

#get devel source folder /devel/source-v${VERSION} 
cd ../source-v${VERSION} 
SRCVRS=$(pwd)
cd -

echo ---
echo "MAIN ${MAIN}"
echo "SRC VERSION ${SRCVRS}"

echo copy /out/lib to main dir /lib
mkdir -p ${MAIN}/lib
rm ${MAIN}/lib/*
cp -p out/lib/* ${MAIN}/lib/

echo update main dir/source

# delete deleted
cd ${MAIN}/source
pwd
for file in *.md; do
    #echo ${file}
    if [ ! -e ${SRCVRS}/${file} ]; then 
        echo deleted: ${file}
        rm ${file}
    fi
done

# update newer sources
echo ${SRCVRS}/ to $(pwd)
cp -uvp ${SRCVRS}/*.lite.md .

cd ${CWD}

#update extras/sublime
mkdir -p ${MAIN}/extras/sublime/LiteScript
cp -uvp /home/ltato/.config/sublime-text-2/Packages/LiteScript/* ${MAIN}/extras/sublime/LiteScript
mkdir -p "${MAIN}/extras/sublime/Theme - Lite Dark"
cp -uvp "/home/ltato/.config/sublime-text-2/Packages/Theme - Lite Dark"/* "${MAIN}/extras/sublime/Theme - Lite Dark"

