#!/bin/bash

set -e

VERSION=$1
if [ "$VERSION" = "" ]; then 
    echo "missing parameter, VERSION. e.g.: copy-to-main 0.7"
    exit 1
fi

CWD=$(pwd)

#get main source folder: ~/LiteScript
cd "../.."
MAIN=$(pwd)
cd -

#get devel source folder /devel/source/v${VERSION} 
cd ../source/v${VERSION} 
SRCVRS=$(pwd)
cd -

echo ---------------
echo UPDATE MAIN DIR: /reference /lib
echo ---------------
echo "MAIN ${MAIN}"
echo "SRC VERSION ${SRCVRS}"
echo ---------------

echo "COPY /out/lib to LS/lib"
rm -rf ${MAIN}/lib/
mkdir -p ${MAIN}/lib
cp -r out/lib/* ${MAIN}/lib/

echo "COPY ${SRCVRS} to LS/reference"
# update sources snapshot
rm -rf ${MAIN}/reference
mkdir -p ${MAIN}/reference
cp  ${SRCVRS}/*.md ${MAIN}/reference/

mkdir -p ${MAIN}/reference/interfaces
cp  ${SRCVRS}/interfaces/*.md ${MAIN}/reference/interfaces

mkdir -p ${MAIN}/reference/lib
cp  ${SRCVRS}/lib/*.md ${MAIN}/reference/lib

cat >${MAIN}/reference/README.md <<end_of_README
LiteScript Compiler Source SNAPSHOT
===================================

###IMPORTANT: development is made at /devel/source/${VERSION}

This dir, /reference, it's just a ***snapshot** of the last released source code: v${VERSION}

Do NOT work on *this dir*, work on [/devel/source/v${VERSION}](/devel/source/v${VERSION})
end_of_README

cd ${CWD}

#update extras/sublime
echo "update extras/sublime"
mkdir -p ${MAIN}/extras/sublime/LiteScript
if [ -d $HOME/.config/sublime-text-2/Packages/LiteScript ]; then 
	cp -up $HOME/.config/sublime-text-2/Packages/LiteScript/*  ${MAIN}/extras/sublime/LiteScript
    rm ${MAIN}/extras/sublime/LiteScript/*.cache
    rm ${MAIN}/extras/sublime/LiteScript/*~
fi
