#!/bin/bash

set -e

VERSION=$1
if [ "$VERSION" = "" ]; then 
    echo "missing parameter, VERSION. e.g.: copy-to-main 0.7"
    exit 1
fi

CWD=$(pwd)

#get main source folder: /source
cd "../.."
MAIN=$(pwd)
cd -

#get devel source folder /devel/source-v${VERSION} 
cd ../source/v${VERSION} 
SRCVRS=$(pwd)
cd -

echo ---------------
echo UPDATE MAIN DIR: /source /lib
echo ---------------
echo "MAIN ${MAIN}"
echo "SRC VERSION ${SRCVRS}"
echo ---------------

echo COPY /out/lib to main dir /lib
mkdir -p ${MAIN}/lib
rm -r ${MAIN}/lib/*
cp -rp out/lib/* ${MAIN}/lib/

# update sources snapshot
rm -r ${MAIN}/source/
cp -r ${SRCVRS}/ ${MAIN}/source/
rm ${MAIN}/source/*.sh
rm ${MAIN}/source/*.json
cat >${MAIN}/source/README.md <<end_of_README
LiteScript Compiler Source SNAPSHOT
===================================

###IMPORTANT: development is made at /devel/source/${VERSION}

This dir, /source, it's just a ***snapshot** of the last released source code: v${VERSION}

Do NOT work on *this dir*, work on [/devel/source/v${VERSION}](devel/source/v${VERSION})
end_of_README

cp -r ${SRCVRS}/ ${MAIN}/source/


cd ${CWD}

#update extras/sublime
mkdir -p ${MAIN}/extras/sublime/LiteScript
if [ -d $HOME/.config/sublime-text-2/Packages/LiteScript ]; then 
	cp -uvp $HOME/.config/sublime-text-2/Packages/LiteScript/*  ${MAIN}/extras/sublime/LiteScript
    rm ${MAIN}/extras/sublime/LiteScript/*.cache
    rm ${MAIN}/extras/sublime/LiteScript/*~
fi
