'Generated by LiteScript compiler v0.8.9, source: interfaces/fs.interface.md
' -----------
Module fs
' -----------
    'export only namespace fs
    Namespace fs
    

        'method exists(path, callback)
        ' ---------------------------
        Public Function exists (path, callback)
        **NO BODY**
        end function
        'method existsSync(path)
        ' ---------------------------
        Public Function existsSync (path)
        **NO BODY**
        end function
        'method readFile(path, options, callback_)
        ' ---------------------------
        Public Function readFile (path, options, callback_)
        **NO BODY**
        end function
        'method readFileSync(path, options)
        ' ---------------------------
        Public Function readFileSync (path, options)
        **NO BODY**
        end function
        'method close(fd, callback)
        ' ---------------------------
        Public Function close (fd, callback)
        **NO BODY**
        end function
        'method closeSync(fd)
        ' ---------------------------
        Public Function closeSync (fd)
        **NO BODY**
        end function
        'method open(path, flags, mode, callback)
        ' ---------------------------
        Public Function open (path, flags, mode, callback)
        **NO BODY**
        end function
        'method openSync(path, flags, mode)
        ' ---------------------------
        Public Function openSync (path, flags, mode)
        **NO BODY**
        end function
        'method read(fd, buffer, offset, length, position, callback)
        ' ---------------------------
        Public Function read (fd, buffer, offset, length, position, callback)
        **NO BODY**
        end function
        'method readSync(fd, buffer, offset, length, position)
        ' ---------------------------
        Public Function readSync (fd, buffer, offset, length, position)
        **NO BODY**
        end function
        'method write(fd, buffer, offset, length, position, callback)
        ' ---------------------------
        Public Function write (fd, buffer, offset, length, position, callback)
        **NO BODY**
        end function
        'method writeSync(fd, buffer, offset, length, position)
        ' ---------------------------
        Public Function writeSync (fd, buffer, offset, length, position)
        **NO BODY**
        end function
        'method rename(oldPath, newPath, callback)
        ' ---------------------------
        Public Function rename (oldPath, newPath, callback)
        **NO BODY**
        end function
        'method renameSync(oldPath, newPath)
        ' ---------------------------
        Public Function renameSync (oldPath, newPath)
        **NO BODY**
        end function
        'method truncate(path, len, callback)
        ' ---------------------------
        Public Function truncate (path, len, callback)
        **NO BODY**
        end function
        'method truncateSync(path, len)
        ' ---------------------------
        Public Function truncateSync (path, len)
        **NO BODY**
        end function
        'method ftruncate(fd, len, callback)
        ' ---------------------------
        Public Function ftruncate (fd, len, callback)
        **NO BODY**
        end function
        'method ftruncateSync(fd, len)
        ' ---------------------------
        Public Function ftruncateSync (fd, len)
        **NO BODY**
        end function
        'method rmdir(path, callback)
        ' ---------------------------
        Public Function rmdir (path, callback)
        **NO BODY**
        end function
        'method rmdirSync(path)
        ' ---------------------------
        Public Function rmdirSync (path)
        **NO BODY**
        end function
        'method fdatasync(fd, callback)
        ' ---------------------------
        Public Function fdatasync (fd, callback)
        **NO BODY**
        end function
        'method fdatasyncSync(fd)
        ' ---------------------------
        Public Function fdatasyncSync (fd)
        **NO BODY**
        end function
        'method fsync(fd, callback)
        ' ---------------------------
        Public Function fsync (fd, callback)
        **NO BODY**
        end function
        'method fsyncSync(fd)
        ' ---------------------------
        Public Function fsyncSync (fd)
        **NO BODY**
        end function
        'method mkdir(path, mode, callback)
        ' ---------------------------
        Public Function mkdir (path, mode, callback)
        **NO BODY**
        end function
        'method mkdirSync(path, mode)
        ' ---------------------------
        Public Function mkdirSync (path, mode)
        **NO BODY**
        end function
        'method readdir(path, callback) returns array
        ' ---------------------------
        Public Function readdir (path, callback)
        **NO BODY**
        end function
        'method readdirSync(path) returns array
        ' ---------------------------
        Public Function readdirSync (path)
        **NO BODY**
        end function
        'method fstat(fd, callback) returns fs.Stats
        ' ---------------------------
        Public Function fstat (fd, callback)
        **NO BODY**
        end function
        'method lstat(path, callback) returns fs.Stats
        ' ---------------------------
        Public Function lstat (path, callback)
        **NO BODY**
        end function
        'method stat(path, callback)  returns fs.Stats
        ' ---------------------------
        Public Function stat (path, callback)
        **NO BODY**
        end function
        'method fstatSync(fd) returns fs.Stats
        ' ---------------------------
        Public Function fstatSync (fd)
        **NO BODY**
        end function
        'method lstatSync(path) returns fs.Stats
        ' ---------------------------
        Public Function lstatSync (path)
        **NO BODY**
        end function
        'method statSync(path) returns fs.Stats
        ' ---------------------------
        Public Function statSync (path)
        **NO BODY**
        end function
        'method readlink(path, callback)
        ' ---------------------------
        Public Function readlink (path, callback)
        **NO BODY**
        end function
        'method readlinkSync(path)
        ' ---------------------------
        Public Function readlinkSync (path)
        **NO BODY**
        end function
        'method symlink(destination, path, type_, callback)
        ' ---------------------------
        Public Function symlink (destination, path, type_, callback)
        **NO BODY**
        end function
        'method symlinkSync(destination, path, type)
        ' ---------------------------
        Public Function symlinkSync (destination, path, type)
        **NO BODY**
        end function
        'method link(srcpath, dstpath, callback)
        ' ---------------------------
        Public Function link (srcpath, dstpath, callback)
        **NO BODY**
        end function
        'method linkSync(srcpath, dstpath)
        ' ---------------------------
        Public Function linkSync (srcpath, dstpath)
        **NO BODY**
        end function
        'method unlink(path, callback)
        ' ---------------------------
        Public Function unlink (path, callback)
        **NO BODY**
        end function
        'method unlinkSync(path)
        ' ---------------------------
        Public Function unlinkSync (path)
        **NO BODY**
        end function
        'method fchmod(fd, mode, callback)
        ' ---------------------------
        Public Function fchmod (fd, mode, callback)
        **NO BODY**
        end function
        'method fchmodSync(fd, mode)
        ' ---------------------------
        Public Function fchmodSync (fd, mode)
        **NO BODY**
        end function
        'method chmod(path, mode, callback)
        ' ---------------------------
        Public Function chmod (path, mode, callback)
        **NO BODY**
        end function
        'method chmodSync(path, mode)
        ' ---------------------------
        Public Function chmodSync (path, mode)
        **NO BODY**
        end function
        'method fchown(fd, uid, gid, callback)
        ' ---------------------------
        Public Function fchown (fd, uid, gid, callback)
        **NO BODY**
        end function
        'method fchownSync(fd, uid, gid)
        ' ---------------------------
        Public Function fchownSync (fd, uid, gid)
        **NO BODY**
        end function
        'method chown(path, uid, gid, callback)
        ' ---------------------------
        Public Function chown (path, uid, gid, callback)
        **NO BODY**
        end function
        'method chownSync(path, uid, gid)
        ' ---------------------------
        Public Function chownSync (path, uid, gid)
        **NO BODY**
        end function
        'method utimes(path, atime, mtime, callback)
        ' ---------------------------
        Public Function utimes (path, atime, mtime, callback)
        **NO BODY**
        end function
        'method utimesSync(path, atime, mtime)
        ' ---------------------------
        Public Function utimesSync (path, atime, mtime)
        **NO BODY**
        end function
        'method futimes(fd, atime, mtime, callback)
        ' ---------------------------
        Public Function futimes (fd, atime, mtime, callback)
        **NO BODY**
        end function
        'method futimesSync(fd, atime, mtime)
        ' ---------------------------
        Public Function futimesSync (fd, atime, mtime)
        **NO BODY**
        end function
        'method writeFile(path, data, options, callback)
        ' ---------------------------
        Public Function writeFile (path, data, options, callback)
        **NO BODY**
        end function
        'method writeFileSync(path, data, options)
        ' ---------------------------
        Public Function writeFileSync (path, data, options)
        **NO BODY**
        end function
        'method appendFile(path, data, options, callback_)
        ' ---------------------------
        Public Function appendFile (path, data, options, callback_)
        **NO BODY**
        end function
        'method appendFileSync(path, data, options)
        ' ---------------------------
        Public Function appendFileSync (path, data, options)
        **NO BODY**
        end function
        'method watch(filename)
        ' ---------------------------
        Public Function watch (filename)
        **NO BODY**
        end function
        'method watchFile(filename)
        ' ---------------------------
        Public Function watchFile (filename)
        **NO BODY**
        end function
        'method unwatchFile(filename, listener)
        ' ---------------------------
        Public Function unwatchFile (filename, listener)
        **NO BODY**
        end function
        'method realpathSync(p, cache)
        ' ---------------------------
        Public Function realpathSync (p, cache)
        **NO BODY**
        end function
        'method realpath(p, cache, cb)
        ' ---------------------------
        Public Function realpath (p, cache, cb)
        **NO BODY**
        end function
        'method createReadStream(path, options)
        ' ---------------------------
        Public Function createReadStream (path, options)
        **NO BODY**
        end function
        'method createWriteStream(path, options)
        ' ---------------------------
        Public Function createWriteStream (path, options)
        **NO BODY**
        end function


        'class Stats
        ' constructor
        Class Stats
        
        Sub New()
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function isDirectory ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isFile ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isBlockDevice ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isCharacterDevice ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isSymbolicLink ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isFIFO ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function isSocket ()
            **NO BODY**
            end function
        
        end class 'Stats


        'class ReadStream
        ' constructor
        Class ReadStream
        
        Sub New(path, options)
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function open ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroy ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function close (cb)
            **NO BODY**
            end function
        
        end class 'ReadStream


        'class FileReadStream
        ' constructor
        Class FileReadStream
        
        Sub New(path, options)
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function open ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroy ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function close (cb)
            **NO BODY**
            end function
        
        end class 'FileReadStream


        'class WriteStream
        ' constructor
        Class WriteStream
        
        Sub New(path, options)
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function open ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroy ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function close (cb)
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroySoon (chunk, encoding, cb)
            **NO BODY**
            end function
        
        end class 'WriteStream


        'class FileWriteStream
        ' constructor
        Class FileWriteStream
        
        Sub New(path, options)
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function open ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroy ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function close (cb)
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroySoon (chunk, encoding, cb)
            **NO BODY**
            end function
        
        end class 'FileWriteStream


        'class SyncWriteStream
        ' constructor
        Class SyncWriteStream
        
        Sub New(fd)
            **NO BODY**
            end function
        
            ' ---------------------------
            Public Function write (data, arg1, arg2)
            **NO BODY**
            end function
            ' ---------------------------
            Public Function end (data, arg1, arg2)
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroy ()
            **NO BODY**
            end function
            ' ---------------------------
            Public Function destroySoon ()
            **NO BODY**
            end function
        
        end class 'SyncWriteStream
        
' -----------
' Module code
' -----------
end module
