'Generated by LiteScript compiler v0.8.9, source: interfaces/path.interface.md
' -----------
Module path
' -----------
'##node.js core  module "path" interface

'Translated to Litescript from node's sources, https://github.com/joyent/node/edit/master/lib/path.js

    'public var sep // POSIX = '/', windows="\""
    Dim sep = Nothing
    'public var delimiter // POSIX= ':', windows = ";"
    Dim delimiter = Nothing

    'public function resolve returns string
    ' ---------------------------
    function resolve()
    **NO BODY**
    end function

    'public function normalize(path)  returns string
    ' ---------------------------
    function normalize(path)
    **NO BODY**
    end function

    'public function isAbsolute(path:string)  //return path.charAt(0) is '/'
    ' ---------------------------
    function isAbsolute(path)
    **NO BODY**
    end function

    'public function join returns string
    ' ---------------------------
    function join()
    **NO BODY**
    end function

    'public function relative(from:string, toPath:string)  returns string
    ' ---------------------------
    function relative(from, toPath)
    **NO BODY**
    end function

    'public function dirname(path) returns string
    ' ---------------------------
    function dirname(path)
    **NO BODY**
    end function

    'public function basename(path:string, ext:string)  returns string
    ' ---------------------------
    function basename(path, ext)
    **NO BODY**
    end function

    'public function extname(path)  returns string
    ' ---------------------------
    function extname(path)
    **NO BODY**
    end function
' -----------
' Module code
' -----------
end module
